### ISSUE TITLE
Allow UrlFor fields to fail somehow

### ISSUE THREAD

**Issue by RobinRamael** [marshmallow-code/flask-marshmallow#18]
I'm trying to render HATEOAS links for a user that may or may not have the attribute `avatar_filename`. When the user does not have that attribute or it is None, it would be nice to just skip the rendering of the field all together. Is it possible to do this in some way? Or if not, would this be something that I could help implement?

**Comment by johnchristopherjones** [comment]
I believe the suggested behavior should be the correct behavior.  I think the problem is that the `ma.URLFor("thingies.thingy" id="<thingattribute>">` syntax raises an error if `thingattribute` isn't set on `thingy`.  By contrast, if an attribute is missing for a fields set with a Marshmallow field type that field is just omitted on serialization.

**Comment by hachaboob** [comment]
I would like to see something configurable for Schemas (probably by using a base Schema class) which you could set whether you wanted the field which caused an AttributeError omitted entirely or set to None/null.

**Comment by joshfriend** [comment]
I've used marshmallow by itself for quite a while now, but just started to try out the `flask-marshmallow` integration. I got stuck on this problem almost immediately. I'm sure I can figure out a way around it somehow but it's kindof a dealbreaker as is

**Comment by sloria** [comment]
Sorry for the delay on this. This is now fixed in 0.10.0.
