### ISSUE TITLE
jsonify a list of objects doesn't work

### ISSUE THREAD

**Issue by genxstylez** [marshmallow-code/flask-marshmallow#31]
```
@app.route('/api/users/')
def users():
    all_users = User.all()
    result = users_schema.dump(all_users)
    return jsonify(result.data)
    # OR
    # return user_schema.jsonify(all_users)
```

the above example raises 
`ValueError: dictionary update sequence element #0 has length 3; 2 is required`

**Comment by jeffwidman** [comment]
This is a Flask issue due to a security vulnerability with old browsers, not a marshmallow issue. 

They're planning to change it since modern browsers aren't vulnerable:
https://github.com/mitsuhiko/flask/issues/248

For a workaround, see: http://stackoverflow.com/questions/12435297/how-do-i-jsonify-a-list-in-flask

**Comment by genxstylez** [comment]
thx, will try it out

**Comment by jeffwidman** [comment]
FYI--I fixed this upstream: https://github.com/mitsuhiko/flask/pull/1671

Flask's `jsonify()` method now serializes top-level arrays. Details here: http://flask.pocoo.org/docs/dev/api/#flask.json.jsonify
