### ISSUE TITLE
Schema.loads().data return dictionary instead of SQLAlchemy Object

### ISSUE THREAD

**Issue by ffleandro** [marshmallow-code/flask-marshmallow#34]
I'm trying to deserialize a json object in a `POST` request into an `SQLAlchemy Model` object.

```
class UserSchema(ma.Schema):
  class Meta:
    model = User
UserSerializer = UserSchema()

(inside my Flask-Restful Post method)
json = request.get_json()
user = UserSerializer.load(json).data
```

After the deserialization, user is an empty dictionary and not an `SQLAlchemy Model` object.
If I manually add the fields to the `UserSchema` declaration, it works, however returns a `dictionary` instead of a `SQLAlchemy Model` object:

```
class UserSchema(ma.Schema):
  class Meta:
    model = User
    fields = ('email', 'password', 'first_name', 'last_name', 'birth_date')
```

Do I need to configure anything else in my `UserSchema`?

I have debugged the `Flask-Marshmallow` initialization, and the `has_sqla` flag is True.

**Comment by keathmilligan** [comment]
I don't think this is a problem with flask-marshmallow, but probably marshmallow-sqlalchemy. It appears to silently fall back to returning a dictionary when something fails in the translation. In my case, it was because the input dict included a "None" value for id. I used 'field_for' to make id a dump only field:

``` python
from marshmallow_sqlalchemy import field_for

class UserSchema(ma.ModelSchema):
    id = field_for(User, 'id', dump_only=True)

    class Meta:
        model = User
```

**Comment by mikekitur** [comment]
hi ffleandro,

do you get this to work? can shared your code, wanted to use the method to load as SQLAlchemy Model object.

Thanks

**Comment by LBWright** [comment]
I get the same issues. It seems to happen when my data is invalid. If the data is valid, there's no issue.
I looked through the unit tests to see if there is a test for it and it's missing the suite of validation tests.
How are things with this project? Do you need more contributors or help?

**Comment by srikrishna-avasarala** [comment]
> I don't think this is a problem with flask-marshmallow, but probably marshmallow-sqlalchemy. It appears to silently fall back to returning a dictionary when something fails in the translation. In my case, it was because the input dict included a "None" value for id. I used 'field_for' to make id a dump only field:
> 
> ```python
> from marshmallow_sqlalchemy import field_for
> 
> class UserSchema(ma.ModelSchema):
>     id = field_for(User, 'id', dump_only=True)
> 
>     class Meta:
>         model = User
> ```

Tried the ModelSchema, and works fine. But this class is now deprecated in marshmallow_sqlalchemy. And the API docs suggests to use SQLAlchemyAutoSchema instead. But use of SQLAlchemyAutoSchema renders the same error (for which this bug is raised) when load() method is called...  Even if we try to use ModelSchema (of marshmallow_sqlalchemy) , we lose the opportunity to use HATEOAS ( _links ) of SQLAlchemyAutoSchema (of flask_marshmallow). Hence I ended up with two schema one for dump (using SQLAlchemyAutoSchema) and other for load (using ModelSchema).  

I guess there should be a permanent fix to this bug so that flask_marshmallow can claim to be both serialization and de-serialization lib.

**Comment by keathmilligan** [comment]
Ran into this one again too updating some old projects. As you found, you should use SQLAlchemyAutoSchema as a replacement for ModelSchema, but yguou also need to add "load_instance = True" in the options, e.g:

```python
from marshmallow_sqlalchemy import field_for

class UserSchema(ma.SQLAlchemyAutoSchema):
    id = field_for(User, 'id', dump_only=True)

    class Meta:
        model = User
        load_instance = True
```
